name: "Validate YAML"
description: "Validate YAML files against a strict schema"
author: "Britton Hayes"
inputs:
  files:
    description: "Files to validate"
    required: true
  schemaPath:
    description: "Path to schema to validate against"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  color: blue
  icon: check-circle
