name: "automerge"
on:
  pull_request:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - uses: ahmadnassri/action-dependabot-auto-merge@v2
      with:
        github-token: ${{ secrets.DEPENDABOT_PUBLIC_TOKEN }}